
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Cổng AMQP (Spring Boot sẽ dùng cổng này)
      - "15672:15672"    # Cổng UI web (để bạn xem queue, message...)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
