server:
  port: 8090

spring:
  application:
    name: recruitment-service

  datasource:
    url: jdbc:mariadb://localhost:3306/recruitment_service
    username: root
    password: fred
    driver-class-name: org.mariadb.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: recruitment_service

mybatis:
  config-location: classpath:mybatis/mybatis_config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.internship.recruitment_service.model

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#     defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.internship.recruitment_service.mapper: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG

profile-service:
  url: http://18.140.1.2:8888